/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



public class IMC extends javax.swing.JFrame {

    /**
     * Creates new form IMC
     */
    public IMC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PESO = new javax.swing.JTextField();
        R = new javax.swing.JLabel();
        RESULTADO = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ESTATURA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CALCULAR = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        PESO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PESOActionPerformed(evt);
            }
        });
        jPanel1.add(PESO);
        PESO.setBounds(440, 170, 90, 30);

        R.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        R.setText("TU IMC ES DE:");
        jPanel1.add(R);
        R.setBounds(340, 260, 110, 30);
        jPanel1.add(RESULTADO);
        RESULTADO.setBounds(440, 260, 110, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/atras.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(30, 330, 50, 50);

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jButton1.setText("CONTINUAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(470, 330, 130, 40);

        ESTATURA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESTATURAActionPerformed(evt);
            }
        });
        jPanel1.add(ESTATURA);
        ESTATURA.setBounds(440, 130, 90, 30);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel1.setText("ESTATURA (METROS):");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(280, 120, 210, 40);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel2.setText("PESO (KG) :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(340, 170, 100, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/pngwing_opt.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, -20, 420, 430);

        CALCULAR.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        CALCULAR.setText("CALCULAR");
        CALCULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULARActionPerformed(evt);
            }
        });
        jPanel1.add(CALCULAR);
        CALCULAR.setBounds(440, 210, 100, 29);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/accesorios-mujer-gimnasio-fitness-coleccion-color-rosa-sobre-fondo-violeta_1428-2165.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 620, 420);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 620, 430);

        jTextField3.setText("jTextField2");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(190, 100, 90, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       MENUMATERIAS abrir=new MENUMATERIAS();
       abrir.setVisible (true);
       this.setVisible (false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PESOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PESOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PESOActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      NUTRICIONMENTESANA abrir=new NUTRICIONMENTESANA();
       abrir.setVisible (true);
       this.setVisible (false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ESTATURAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESTATURAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ESTATURAActionPerformed

    private void CALCULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULARActionPerformed
        double E,P,R;
        E=Double.parseDouble(ESTATURA.getText());
        P=Double.parseDouble(PESO.getText());
        R= P/(E*E);
        RESULTADO.setText(String.valueOf(R));
// TODO add your handling code here:
    }//GEN-LAST:event_CALCULARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CALCULAR;
    private javax.swing.JTextField ESTATURA;
    private javax.swing.JTextField PESO;
    private javax.swing.JLabel R;
    private javax.swing.JTextField RESULTADO;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
