/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aleji
 */
public class NUTRICIONMENTESANA extends javax.swing.JFrame {

    /**
     * Creates new form NUTRICIONMENTESANA
     */
    public NUTRICIONMENTESANA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnusuario = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 60)); // NOI18N
        jLabel1.setText("BIENVENIDOS!!");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(50, 0, 550, 150);

        jLabel4.setFont(new java.awt.Font("Castellar", 1, 14)); // NOI18N
        jLabel4.setText("bY: ANA SOTO CATALINA TRUJILLO Y LAURA PACHECO");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 160, 560, 90);

        jLabel6.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel6.setText("CUERPO SANO");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(300, 120, 440, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/usuario (1).png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(520, 310, 64, 130);

        btnusuario.setBackground(new java.awt.Color(255, 153, 204));
        btnusuario.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        btnusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/accesorios-mujer-gimnasio-fitness-coleccion-color-rosa-sobre-fondo-violeta_1428-2165.jpg"))); // NOI18N
        btnusuario.setText("USUARIO");
        btnusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusuarioActionPerformed(evt);
            }
        });
        jPanel2.add(btnusuario);
        btnusuario.setBounds(490, 340, 120, 70);

        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 380, 73, 23);

        jLabel7.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel7.setText("MENTE SANA EN");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 80, 560, 90);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/deporte-plano-pone-fondo-rosa_1220-3858.jpg"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 630, 420);

        jLabel8.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel8.setText("MENTE SANA EN");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(40, 110, 560, 90);

        jLabel9.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel9.setText("MENTE SANA EN");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(30, 110, 560, 90);

        jLabel10.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel10.setText("CUERPO SANO");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(300, 150, 440, 90);

        jLabel11.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel11.setText("CUERPO SANO");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(300, 160, 440, 90);

        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(440, 260, 34, 14);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 630, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    private void btnusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusuarioActionPerformed
      USUARIOS abrir=new USUARIOS();
       abrir.setVisible (true);
       this.setVisible (false);
    }//GEN-LAST:event_btnusuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NUTRICIONMENTESANA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NUTRICIONMENTESANA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NUTRICIONMENTESANA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NUTRICIONMENTESANA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NUTRICIONMENTESANA().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnusuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
