/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aleji
 */
public class QUIMIC extends javax.swing.JFrame {

    /**
     * Creates new form QUIMIC
     */
    public QUIMIC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Captura de pantalla 2021-01-21 a las 17_opt (1).png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 350, 230);

        jTextPane1.setText("si tu IMC ES mayor a 25 debes tener cuidado, vas por un sobrepeso preocupante, debes alinear tus comidas, reduce el consumo de noche, procede a hacer ejercicios diarios así sean cortos, consume mucha agua para que la grasa no se infle y sea más facil de perderla. ");
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(450, 190, 290, 30);

        jTextPane2.setText("Si tu IMC fué menor a 18 debes tener en cuenta que estas en bajo peso, cuidate, y en tus comidas diarias reponte con menus equilibrados con porteinas y carbohidratos, donde los lípidos los tengas en cuenta pero en menor cantidad");
        jScrollPane2.setViewportView(jTextPane2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(450, 100, 290, 30);

        jTextPane3.setText("si tu IMC ES 18 A 25 felicidades tienes un peso normal pero no te descuides, sigue comiendo saludable y ejercitandote como debe ser.");
        jScrollPane3.setViewportView(jTextPane3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(450, 60, 290, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/atras.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 420, 50, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Captura de pantalla 2021-01-21 a las 17_opt (2).png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(420, 240, 400, 231);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Captura de pantalla 2021-01-21 a las 17_opt.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 240, 400, 230);

        jTextPane4.setText("si tu IMC ES mayor a 30 debes empezar a preocuparte, necesitas una buena alimentació, reduce al máximo los carbohidratos , y lo lípidos que sean necesarios en algunas comidas, no elimines las proteinas y vegetales, serán tu mejor amigo, cuidate, nuestro cuerpo es un templo y debemos cuidarlo.");
        jScrollPane4.setViewportView(jTextPane4);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(450, 140, 290, 30);

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 36)); // NOI18N
        jLabel4.setText("RECOMENDACIÓNES");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(400, 10, 400, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MENUMATERIAS abrir=new MENUMATERIAS ();
       abrir.setVisible (true);
       this.setVisible (false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QUIMIC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QUIMIC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QUIMIC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QUIMIC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QUIMIC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    // End of variables declaration//GEN-END:variables
}
