/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aleji
 */
public class USUARIOS extends javax.swing.JFrame {

    /**
     * Creates new form USUARIOS
     */
    public USUARIOS() {
        initComponents();
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btningresarusuario = new javax.swing.JButton();
        btnatrasusuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        btningresarusuario.setBackground(new java.awt.Color(255, 153, 153));
        btningresarusuario.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        btningresarusuario.setText("INGRESAR");
        btningresarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarusuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btningresarusuario);
        btningresarusuario.setBounds(470, 340, 140, 50);

        btnatrasusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/atras.png"))); // NOI18N
        btnatrasusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasusuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnatrasusuario);
        btnatrasusuario.setBounds(20, 350, 60, 50);

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USUARIO:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 120, 130, 30);

        jLabel2.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CODIGO EMPRESA:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 180, 230, 31);

        jPasswordField1.setText("jPasswordField1");
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(310, 180, 170, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(310, 120, 170, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/flat-lay-sport-concept-equipo-vida-sana-fondo-vibrante-oscuro-primer-plano-espacio-copia_1309-241.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 630, 420);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 850, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnatrasusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasusuarioActionPerformed
         NUTRICIONMENTESANA abrir=new  NUTRICIONMENTESANA ();
       abrir.setVisible (true);
       this.setVisible (false); // TODO add your handling code here:
    }//GEN-LAST:event_btnatrasusuarioActionPerformed

    private void btningresarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarusuarioActionPerformed
      String usuario="ComfandiMiraflores";
      String contra="22222";
      String cla=new String(jPasswordField1.getPassword());
      
        if (jTextField1.getText().equals(usuario)&& cla.equals(contra)){ 
            
            IMC abrir=new IMC();
            abrir.setVisible (true);
            this.setVisible (false);
        }
        else 
       JOptionPane.showMessageDialog(null,"Contraseña y usuario incorrectos");
    }//GEN-LAST:event_btningresarusuarioActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
       
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(USUARIOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(USUARIOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(USUARIOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(USUARIOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new USUARIOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnatrasusuario;
    private javax.swing.JButton btningresarusuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private static class JOptionPane {

        private static void showMessageDialog(Object object, String codigo_de_empresa_incorrecta_verifique) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public JOptionPane() {
        }
    }
}
